homeassistant:
  # Name of the location where Home Assistant is running
  name: Tree House
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 12
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Sensors
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature  
  # - platform: cpuspeed
  - platform: speedtest
    minute:
      - 0
      - 30  
    monitored_conditions:
      - ping
      - download
      - upload  
  - platform: glances
    host: 10.13.37.179
    port: 8123
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'


  # - platform: yweather
  #   monitored_conditions:
  #     - weather
  #     - weather_current
  #     - temp_min
  #     - temp_max
  #     - wind_speed
  #     - pressure
  #     - visibility
  #     - humidity
  #     - temperature





# Integrations
# -----------------------------------------


# Automatic
device_tracker:
  - platform: automatic
    client_id: !secret automatic_id
    secret: !secret automatic_secret
    username: !secret automatic_username
    password: !secret automatic_password


# Yahoo Weather
# sensor:
  # - platform: yweather
  #   monitored_conditions:
  #     - weather
  #     - weather_current
  #     - temp_min
  #     - temp_max
  #     - wind_speed
  #     - pressure
  #     - visibility
  #     - humidity
  #     - temperature


# Uber

# Weather Underground

# Echo





# Automation
# -----------------------------------------
