homeassistant:
  # Name of the location where Home Assistant is running
  name: Tree House
  # Location required to calculate the time the sun rises and sets
  latitude: 39.9383587
  longitude: -75.1600286
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 12
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr


# Integrations
# -----------------------------------------


# Automatic
device_tracker:
  - platform: automatic
    client_id: !secret automatic_id
    secret: !secret automatic_secret
    username: !secret automatic_username
    password: !secret automatic_password


# Uber


# Weather Underground


# Echo
# alexa:
#   intents:
#     ActivateSceneIntent:
#       action:
#         service: scene.turn_on
#         data_template:
#           entity_id: scene.{{ Scene | replace(" ", "_") }}
#       speech:
#         type: plaintext
#         text: OK



# Automation
# -----------------------------------------

# Using the sun
# automation:
#   trigger:
#     platform: sun
#     event: sunset
#     offset: "-00:45:00"
#   condition:
#     condition: state
#     # entity_id: group.all_devices
#     entity_id: light.kitchen_light
#     state: off
#   action:
#     service: homeassistant.turn_on
#     entity_id: group.living_room_lights




